slogan: "Yet another System Engineering blog\n\r\0"

theme: cerulean
inverse: true

menu:
  - title: Archives
    url: archives
    intro: "All the articles."
    icon: "fa fa-archive"
  - title: Categories
    url: categories
    intro: "All the categories."
    icon: "fa fa-folder"
  - title: Tags
    url: tags
    intro: "All the tags."
    icon: "fa fa-tags"
  - title: About
    url: 2015/10/10/About-This-Blog/
    intro: "About me."
    icon: "fa fa-user"

links:
  - title: "My Github"
    url: http://www.github.com/gotoco
    intro: "My Github account."
    icon: "fa fa-github"
  - title: "My LinkedIn"
    url: https://www.linkedin.com/in/maciej-grochowski-94a03a54
    intro: "My Linkin account."
    icon: "fa fa-linkedin"
  - title: "My Twitter"
    url: https://twitter.com/mathfriday
    intro: "My Twitter account."
    icon: "fa fa-twitter"
  - title: Freemind-Theme
    url: https://github.com/wzpan/freemind/
    intro: "Freemind's Github repository."
    icon: "fa fa-github"

widgets:
- search
- recent_comments
- category
- tagcloud
- recent_posts
- links

rss:
fancybox: true
favicon: favicon.png
duoshuo_shortname: #freemindtheme

# Recommended posts
# Dependency: https://github.com/huiwang/hexo-recommended-posts
recommended_posts:
  enabled: false

# Analytics
google_analytics:
  enable: false
  siteid:
baidu_tongji:
  enable: false
  siteid:

# search
# swiftype_key: ZP2ZSuHgipSZfRyU8uTR

# share widgets
bdshare: true
jiathis: false

# built-in comment system
comment_js:
  type: "github"
  user: "gotoco"
  repo: "blog"
  client_id: "497153997fa884503f67"
  client_secret: "4ba4664b5d1adbb607ec317551cbd67856de17b8"
  count: 5
